# Generated by Django 4.1.7 on 2023-03-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_userlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
