# Generated by Django 4.1.7 on 2023-03-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userlog_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='status',
        ),
    ]
